### ISSUE TITLE
Use MediaObject instead of DigitalDocument

### ISSUE THREAD

**Issue by alastair** [trompamusic/ce-musicbrainz-import#4]
as suggested by @musicog

**Comment by musicog** [comment]
To be clear:

* Use MediaObjects for things like score PDFs and music encodings (MEI, MusicXML), making judicious use of schema:encodesCreativeWork and schema:encodingFormat. 

* Use schema:contentUrl to reference raw data where possible, particularly if it differs from the MediaObjects' URI (e.g., a permalink to an IMSLP entry for a score PDF, vs. a link to the actual corresponding PDF file)

* Where direct linking is impossible because the relevant file is located within a compressed archive (e.g. the common situation of a MusicXML encoding inside a zip file), we will need to model the zip file and its contained encoding file separately. Precise mechanism to be determined, but working proposal:

  * Zip file modelled as a schema:DigitalDocument
  * MusicXML file inside the zip file modelled as a schema:MediaObject 
  * MusicXML file's contentUrl is an [arcp://]( http://s11.no/2018/arcp.html) URI targetting location inside the source zip file
   * MusicXML file has a dc:source relationship with the Zip file
